Repository ccmbioinfo/osmp, pull requests merged in 2022-06, with the labels that each got.

#259 Documentation: Update README page.
  README.md
Labels: documentation

#266 React: Modify "Affected Status" and "Phenotypes" columns
  react/src/components/Table/PhenotypeViewer.tsx
  react/src/components/Table/Table.tsx
Labels: react

#279 Bug: Fix a bug with the column group divider
  react/src/components/Table/Table.tsx
  react/src/utils/tableHelpers.ts
Labels: bug
